# Generated by Django 2.2.6 on 2020-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200705_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='user',
            field=models.ManyToManyField(to='api_basic.User'),
        ),
    ]
